# Generated by Django 4.2.4 on 2023-10-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='archived_events',
            new_name='visited_events',
        ),
    ]
