# Generated by Django 4.2.4 on 2023-10-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haka_app', '0003_alter_event_can_subscribe'),
        ('auth_app', '0004_rename_archived_events_userprofile_visited_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='future_events',
            field=models.ManyToManyField(blank=True, related_name='subscribed_event', to='haka_app.event'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='visited_events',
            field=models.ManyToManyField(blank=True, related_name='archived_event', to='haka_app.event'),
        ),
    ]
