# Generated by Django 4.2.4 on 2023-10-04 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_anonymoususer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anonymoususer',
            old_name='ip_adress',
            new_name='ip_address',
        ),
    ]
