# Generated by Django 4.2.4 on 2023-10-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_tag_userpublication_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='img',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='userpublication',
            name='img',
            field=models.JSONField(default=[]),
        ),
    ]
