# Generated by Django 4.2.4 on 2023-10-06 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haka_app', '0008_event_img'),
        ('auth_app', '0009_userprofile_img_userpublication_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='haka_app.event'),
        ),
    ]
