# Generated by Django 4.2.4 on 2023-10-07 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_userpublication_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='event',
        ),
    ]
