# Generated by Django 4.2.4 on 2023-10-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0018_alter_comment_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
