# Generated by Django 4.2.4 on 2023-10-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haka_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='can_subscribe',
            field=models.CharField(choices=[('all', 'Могут подписаться все'), ('authenticated_users', 'Авторизованные пользователи')], default='all', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='display_to_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='display_to_followers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.JSONField(default={}),
        ),
    ]
