# Generated by Django 4.2.4 on 2023-10-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haka_app', '0002_event_can_subscribe_event_date_event_display_to_all_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='can_subscribe',
            field=models.CharField(choices=[('all', 'Могут подписаться все'), ('authenticated_users', 'Авторизованные пользователи'), ('friends', 'Только друзья')], default='all', max_length=255),
        ),
    ]
