# Generated by Django 4.2.4 on 2023-10-04 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('haka_app', '0003_alter_event_can_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='followers',
            field=models.ManyToManyField(related_name='event_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
