# Generated by Django 4.2.4 on 2023-10-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_rename_ip_adress_anonymoususer_ip_address'),
        ('haka_app', '0004_event_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='anonymous_followers',
            field=models.ManyToManyField(related_name='anonymous_follower', to='auth_app.anonymoususer'),
        ),
    ]
