# Generated by Django 4.2.4 on 2023-10-05 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0008_tag_userpublication_comment'),
        ('haka_app', '0006_alter_event_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='auth_app.tag'),
        ),
        migrations.AlterField(
            model_name='event',
            name='anonymous_followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='anonymous_follower', to='auth_app.anonymoususer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
