# Generated by Django 4.2.4 on 2023-10-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haka_app', '0007_event_is_free_event_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.JSONField(default=[]),
        ),
    ]
