# Generated by Django 4.2.4 on 2023-10-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haka_app', '0012_alter_event_end_event_date_alter_event_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
